[build]
builder = "DOCKERFILE"
dockerfilePath = "pipeline-service/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
